exports.data = {
    "id": 2993,
    "runtime": 60,
    "weight": 99,
    "summary": "<p>A love letter to the '80s classics that captivated a generation, <b>Stranger Things</b> is set in 1983 Indiana, where a young boy vanishes into thin air. As friends, family and local police search for answers, they are drawn into an extraordinary mystery involving top-secret government experiments, terrifying supernatural forces and one very strange little girl.</p>",
    "_embedded": {
        "episodes": [{
            "id": 553946,
            "name": "Chapter One: The Vanishing of Will Byers",
            "season": 1,
            "number": 1,
            "airstamp": "2016-07-15T12:00:00+00:00",
            "runtime": 60,
            "summary":"A young boy mysteriously disappears, and his panicked mother demands that the police find him"
        }, {
            "id": 578663,
            "name": "Chapter Two: The Weirdo on Maple Street",
            "season": 1,
            "number": 2,
            "airstamp": "2016-07-15T12:00:00+00:00",
            "runtime": 60,
            "summary": "<p>While the search for the missing Will continues, Joyce tells Jim about a call she apparently received from her son. Meanwhile, Jane warns Mike that there are bad people after her, and he realizes that she knows what happened to Will.</p>",
        }, {
            "id": 578664,
            "name": "Chapter Three: Holly, Jolly",
            "season": 1,
            "number": 3,
            "airstamp": "2016-07-15T12:00:00+00:00",
            "runtime": 60,
            "summary": "<p>While Nancy looks for a missing Barbara and realizes that Jonathan may have been the last person to see her, Mike and his friends go out with Jane to find the missing Will. Meanwhile, Jim tracks Will to the lab.</p>",
        }, {
            "id": 578665,
            "season": 1,
            "number": 4,
            "airstamp": "2016-07-15T12:00:00+00:00",
            "runtime": 60,
            "summary": "<p>Jim realizes that the government is covering something up about Will's death and begins a personal investigation. Meanwhile, Nancy discovers that Jonathan has information about Barbara's disappearance, while Mike and his friends smuggle Jane into the school so she can use the ham radio to contact Will.</p>",
        }, {
            "id": 578666,
            "name": "Chapter Five: The Flea and the Acrobat",
            "season": 1,
            "number": 5,
            "airstamp": "2016-07-15T12:00:00+00:00",
            "runtime": 60,
            "summary": "<p>Jim searches for Will at Hawkins Laboratory, but finds something unexpected. Meanwhile, Lonnie helps Joyce bury Will but reveals an ulterior motive for returning to town, while the boys find a way to locate Will but discover that Jane is opposing them.</p>",
        }, {
            "id": 578667,
            "name": "Chapter Six: The Monster",
            "season": 1,
            "number": 6,
            "airstamp": "2016-07-15T12:00:00+00:00",
            "runtime": 60,
            "summary": "<p>Jonathan manages to pull Nancy back to the real world from the Upside Down. Meanwhile, Lucas refuses to help with the search for Jane and goes to Hawkins Labs on his own, while Dustin and Mike look for the missing girl.</p>",
        }, {
            "id": 578668,
            "name": "Chapter Seven: The Bathtub",
            "season": 1,
            "number": 7,
            "airstamp": "2016-07-15T12:00:00+00:00",
            "runtime": 60,
            "summary": "<p>Jim manages to bring everyone together so that they can join forces to reconnect Jane to the Upside Down and find Will. Meanwhile, the government closes in on Jane and the boys.</p>",
        }, {
            "id": 578669,
            "name": "Chapter Eight: The Upside Down",
            "season": 1,
            "number": 8,
            "airstamp": "2016-07-15T12:00:00+00:00",
            "runtime": 60,
            "summary": "<p>Jim convinces Brenner to let him and Joyce enter the Upside Down to find Will... unaware that Brenner plans to recover Jane no matter what it takes. Meanwhile, Nancy and Jonathan prepare to trap the monster at the Byers house, but receive an unexpected visitor.</p>",
        }, {
            "id": 909340,
            "name": "Chapter One: MADMAX",
            "season": 2,
            "number": 1,
            "airstamp": "2017-10-27T12:00:00+00:00",
            "runtime": 60,
            "summary": "<p>One year after the events with the Upside Down and the Demogorgon, Will meets with a government doctor. The boys discover that there's a new player in town, and Jim pays a visit to El.</p>",
        }, {
            "id": 909342,
            "name": "Chapter Two: Trick or Treat, Freak",
            "season": 2,
            "number": 2,
            "airstamp": "2017-10-27T12:00:00+00:00",
            "runtime": 60,
            "summary": "<p>The boys go trick-or-treating on Halloween, and Will has another vision. Meanwhile, El relieves the days following her escape from the Upside Down, and Dustin finds something in the garbage can.</p>",
        }, {
            "id": 909343,
            "name": "Chapter Three: The Pollywog",
            "season": 2,
            "number": 3,
            "airstamp": "2017-10-27T12:00:00+00:00",
            "runtime": 60,
            "summary": "<p>Dustin takes in a stray and calls it D'Artagnan. However, his plans to show it to Mr. Clarke don't go as intended. Meanwhile, Max tries to convince Mike to let her join the group, El sneaks out to pay her friends a visit, and Will decides to take a stand and face his fears.</p>",
        }, {
            "id": 909344,
            "name": "Chapter Four: Will the Wise",
            "season": 2,
            "number": 4,
            "airstamp": "2017-10-27T12:00:00+00:00",
            "runtime": 60,
            "summary": "<p>After his encounter with the shadow creature, Will's condition worsens. Meanwhile, Jim and El fight after Jim discovers that El disobeyed the rules, and Owens brings Nancy and Jonathan to Hawkins Labs for a chat.</p>",
        }, {
            "id": 909345,
            "name": "Chapter Five: Dig Dug",
            "season": 2,
            "number": 5,
            "airstamp": "2017-10-27T12:00:00+00:00",
            "runtime": 60,
            "summary": "<p>Jim is trapped in the Upside Down, and Joyce enlists Bob to help find him. Meanwhile, Nancy and Jonathan go to Murray, and El learns about the circumstances surrounding her birth.</p>",
        }, {
            "id": 909346,
            "name": "Chapter Six: The Spy",
            "season": 2,
            "number": 6,
            "airstamp": "2017-10-27T12:00:00+00:00",
            "runtime": 60,
            "summary": "<p>Owens and his team try to find a way to end the shadow creature's influence on Will. Meanwhile, Dustin and Lucas find unlikely allies in their quest to find Dart.</p>",
        }, {
            "id": 909347,
            "name": "Chapter Seven: The Lost Sister",
            "season": 2,
            "number": 7,
            "airstamp": "2017-10-27T12:00:00+00:00",
            "runtime": 60,
            "summary": "<p>El travels to Chicago to find her sister Eight, aka Kali, who has teamed up with other outcasts to kill the men who tormented her at Hawkins Labs.</p>",
        }, {
            "id": 909348,
            "name": "Chapter Eight: The Mind Flayer",
            "season": 2,
            "number": 8,
            "airstamp": "2017-10-27T12:00:00+00:00",
            "runtime": 60,
            "summary": "<p>When the demo-dogs overrun Hawkins Labs, one of the group saves the others at the cost of their own life. When the others get back to the Byers house, they realize what they're facing and try to get answers from a captive Will.</p>",
        }, {
            "id": 909349,
            "name": "Chapter Nine: The Gate",
            "season": 2,
            "number": 9,
            "airstamp": "2017-10-27T12:00:00+00:00",
            "runtime": 60,
            "summary": "<p>The group splits up to close the gate, evict the Mind Flayer from Will, and drive the demo-dogs away from Hawkins Lab.</p>",
        }, {
            "id": 1576469,
            "name": "Chapter One: Suzie, Do You Copy?",
            "season": 3,
            "number": 1,
            "airstamp": "2019-07-04T12:00:00+00:00",
            "runtime": 51,
            "summary": "<p>Things change over the summer: Jonathan, Nancy, Steve, and Billy get jobs; Dustin goes to science camp; El and Mike become an item; Lucas and Max almost become an item. Meanwhile, mysterious power outages plague Hawkins and rats start exploding.</p>",
        }, {
            "id": 1576470,
            "name": "Chapter Two: The Mall Rats",
            "season": 3,
            "number": 2,
            "airstamp": "2019-07-04T12:00:00+00:00",
            "runtime": 50,
            "summary": "<p>While El and Max go shopping, Nancy and Wheeler follow up on the exploding rats. Billy takes a coworker on a field trip, and Joyce blows off dinner with Jim to meet with Mr. Clarke.</p>",
        }, {
            "id": 1576471,
            "name": "Chapter Three: The Case of the Missing Lifeguard",
            "season": 3,
            "number": 3,
            "airstamp": "2019-07-04T12:00:00+00:00",
            "runtime": 50,
            "summary": "<p>El goes astrally projecting and discovers that Billy has done something with Heather. While the girls try to find the missing lifeguard, Will tries to get Mike and Lucas interested in D&amp;D. Dustin and Steve spy on the mall shops, and Robin tries to decipher the Russian message.</p>",
        }, {
            "id": 1576472,
            "name": "Chapter Four: The Sauna Test",
            "season": 3,
            "number": 4,
            "airstamp": "2019-07-04T12:00:00+00:00",
            "runtime": 53,
            "summary": "<p>Mike, Lucas, and Will recruit El and Max to help them learn who the Mind Flayer's host is. Robin, Steve, and Dustin recruit someone to sneak into Lynx, and Nancy and Jonathan are fired.</p>",
        }, {
            "id": 1576473,
            "name": "Chapter Five: The Flayed",
            "season": 3,
            "number": 5,
            "airstamp": "2019-07-04T12:00:00+00:00",
            "runtime": 52,
            "summary": "<p>The Scoop Group explore the tunnels beneath Starcourt, while Nancy and Jonathan recruit Mike and the others to help them discover what happen to the Holloways and find the Mind Flayer's base of operations.</p>",
        }, {
            "id": 1576474,
            "name": "Chapter Six: E Pluribus Unum",
            "season": 3,
            "number": 6,
            "airstamp": "2019-07-04T12:00:00+00:00",
            "runtime": 60,
            "summary": "<p>Dr. Alexei reveals what the Russians have been building, and Eleven sees where Billy has been. Dustin and Erica stage a daring rescue.</p>",
        }, {
            "id": 1576475,
            "url": "http://www.tvmaze.com/episodes/1576475/stranger-things-3x07-chapter-seven-the-bite",
            "season": 3,
            "number": 7,
            "airstamp": "2019-07-04T12:00:00+00:00",
            "runtime": 55,
            "summary": "<p>El and the others defend themselves as the Flayer tracks them down. The Scoop Group escape the Russian base and hide in a movie theater, but the Russians close in on them.</p>",
        }, {
            "id": 1576476,
            "name": "Chapter Eight: The Battle of Starcourt",
            "season": 3,
            "number": 8,
            "airstamp": "2019-07-04T12:00:00+00:00",
            "runtime": 78,
            "summary": "<p>The Flayer comes to the mall to get El, and Dustin contacts Suzie to provide Jim and Joyce with needed information. El reminds Billy of his past, and Jim and Joyce have an argument about not arguing.</p>",
        }, {
            "id": 1752754,
            "url": "http://www.tvmaze.com/episodes/1752754/stranger-things-4x01-chapter-one-the-hellfire-club",
            "name": "Chapter One: The Hellfire Club",
            "season": 4,
            "number": 1,
            "airstamp": null,
            "runtime": 60,
            "summary": null,
        }]
    }
}